### PR TITLE
Add max_retries to config, avoid hardcoding it

### PR DESCRIPTION
**Pull request by friendly-bits**
- Better to set max_retries in config rather than hardcode it.
- This PR also implements retry loops without calling external binary (seq).

### CODE REVIEW

**Comment by lynxthecat** [comment]
How about we make it max_download_retries and then we should add it to the checks here:

https://github.com/lynxthecat/adblock-lean/pull/30/files#diff-759db58e0b7adb9f787c6c7b54caff784f1aa99d758c7e458c7d7768f83adb7aR105

**Comment by friendly-bits** [comment]
> How about we make it max_download_retries and then we should add it to the checks here

done

**Comment by friendly-bits** [comment]
Now actually done properly (I think)

**Comment by lynxthecat** [comment]
Looks good.  Please can we change commit message to: 

Add max_download_retries to config file

to keep within the 50 character limit?

**Comment by friendly-bits** [comment]
> Looks good. Please can we change commit message to:
> 
> Add max_download_retries to config file
> 
> to keep within the 50 character limit?

Done

**Pull request merged**
